INSERT  INTO PROPIETARIO (ID,EMAIL_PRO,APELLIDO_PRO,DIRECCION_PRO,NOMBRE_PRO,TELEFONO_PRO) VALUES (1,'ALGO@ALGO.ALGALLO','CARANCHOA','EL BRONX','BENITO','5556677');

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (1,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (2,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (3,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (4,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (5,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (6,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (7,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (8,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (9,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (10,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (11,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (12,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (13,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (14,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (15,'CANINO','MISIFUS','50','PINCHE',1);

INSERT  INTO PACIENTE (CODIGO_PACIENTE,ESPECIE_PTE,NOMBRE_PTE,PESO_PTE,RAZA_PTE,CODIGO_PROPIETARIO_ID) VALUES (16,'CANINO','MISIFUS','50','PINCHE',1);

INSERT INTO HISTORIA_CLINICA (CODIGO_HISTORIA, MEDICAMENTOS, PROCEDIMIENTO, CODIGO_PACIENTE_CODIGO_PACIENTE, CODIGO_PROPIETARIO_ID) VALUES (1,'ACETAMINOFEN','DISPENSACIÓN DE MEDICAMENTO',1,1);


